import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { BoundedWakeCoalescer } from "../lib/world-bridge/coalescer.ts";
import { DeliveryLedger } from "../lib/world-bridge/delivery-ledger.ts";

test("must-handle sources survive coalescer overflow and ledger reopen", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-agent-ledger-"));
  const filename = join(directory, "delivery.sqlite");
  const ids = Array.from({ length: 7 }, (_, index) => `evidence-${index}`);
  let ledger = new DeliveryLedger(filename);
  try {
    const coalescer = new BoundedWakeCoalescer(
      { maxSourceIds: 8, maxDirtyKeys: 8, maxMustHandleIds: 2 },
      (sourceId) => ledger.retainMustHandle(sourceId),
    );
    for (const id of ids) coalescer.enqueue({ sourceId: id, mustHandleId: id });
    const batch = coalescer.drain();
    assert.deepEqual(batch?.mustHandleIds, ids.slice(0, 2));
    assert.equal(batch?.mustHandleBackpressure, true);
    assert.equal(batch?.rescanRequired, false, "rescan cannot stand in for guaranteed handling");
    assert.deepEqual(ledger.listPendingMustHandle({ limit: 32 }), ids);

    // No acknowledgement is generated by coalescing or dispatch acceptance.
    assert.deepEqual(ledger.listPendingMustHandle({ limit: 32 }), ids);
    ledger.close();
    ledger = new DeliveryLedger(filename);
    assert.deepEqual(ledger.listPendingMustHandle({ limit: 32 }), ids);

    // Only an explicit post-handling acknowledgement retires one durable row.
    assert.equal(ledger.acknowledgeMustHandle(ids[0]), true);
    assert.deepEqual(ledger.listPendingMustHandle({ limit: 32 }), ids.slice(1));
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("must-handle coalescing fails closed without durable persistence", () => {
  const coalescer = new BoundedWakeCoalescer({ maxSourceIds: 1, maxDirtyKeys: 1, maxMustHandleIds: 1 });
  assert.throws(
    () => coalescer.enqueue({ sourceId: "source", mustHandleId: "source" }),
    /durable ledger callback/,
  );
});

test("step receipt dedupe uses event id while action intent dedupe uses trusted sequence", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-receipts-"));
  const ledger = new DeliveryLedger(join(directory, "delivery.sqlite"));
  try {
    const step = { sessionId: "session", turnId: "turn", stepIndex: 3 };
    ledger.recordStepHook({ ...step, eventId: "event-a", eventType: "step.started" });
    ledger.recordStepHook({ ...step, eventId: "event-a", eventType: "step.started" });
    ledger.recordStepHook({ ...step, eventId: "event-b", eventType: "step.started" });
    assert.deepEqual(ledger.listStepHooks(step), [
      { eventId: "event-a", eventType: "step.started" },
      { eventId: "event-b", eventType: "step.started" },
    ]);
    const first = ledger.beginActionIntent({ fingerprint: "sha256:fingerprint", invocationSequence: 1 });
    const retry = ledger.beginActionIntent({ fingerprint: "sha256:fingerprint", invocationSequence: 1 });
    const deliberateRepeat = ledger.beginActionIntent({ fingerprint: "sha256:fingerprint", invocationSequence: 2 });
    assert.equal(retry.intentId, first.intentId);
    assert.notEqual(deliberateRepeat.intentId, first.intentId);
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("wake acceptance is bound to the real Eve session and advanced by step start", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-wake-receipt-"));
  const ledger = new DeliveryLedger(join(directory, "delivery.sqlite"));
  try {
    const wake = ledger.beginWake({
      wakeId: "wake-1",
      worldId: "world-1",
      agentId: "agent-1",
      sourceIds: ["world.snapshot"],
      dirtyKeys: ["world.snapshot"],
      mustHandleIds: ["message-1"],
      rescanRequired: false,
    });
    ledger.retainMustHandle("message-1");
    ledger.bindWakeSession(wake.wakeId, "eve-session-1");
    ledger.transitionWake(wake.wakeId, "accepted");
    assert.equal(ledger.acknowledgeWakeForSession("eve-session-1"), 1);
    assert.equal(ledger.getWake(wake.wakeId).status, "context_presented");
    assert.equal(ledger.completeWakeForSession("eve-session-1"), 1);
    assert.equal(ledger.getWake(wake.wakeId).status, "acknowledged");
    assert.deepEqual(ledger.listPendingMustHandle(), ["message-1"], "presentation is not evidence handling");
    assert.equal(ledger.acknowledgeWakeForSession("eve-session-1"), 0);
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("wake ids are random durable identities across ledger reopen, not process generations", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-wake-id-"));
  const filename = join(directory, "delivery.sqlite");
  let ledger = new DeliveryLedger(filename);
  try {
    const first = ledger.beginWake({
      worldId: "world-1",
      agentId: "agent-1",
      sourceIds: ["source-1"],
      dirtyKeys: ["source-1:key"],
      mustHandleIds: [],
      rescanRequired: false,
    });
    ledger.close();
    ledger = new DeliveryLedger(filename);
    const second = ledger.beginWake({
      worldId: "world-1",
      agentId: "agent-1",
      sourceIds: ["source-2"],
      dirtyKeys: ["source-2:key"],
      mustHandleIds: [],
      rescanRequired: false,
    });
    assert.notEqual(second.wakeId, first.wakeId);
    assert.equal(ledger.getWake(first.wakeId).status, "pending");
    assert.equal(ledger.getWake(second.wakeId).status, "pending");
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("turn activity is idempotent when turn.started races send return and repeats", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-turn-activity-"));
  const ledger = new DeliveryLedger(join(directory, "delivery.sqlite"));
  try {
    // Eve can publish turn.started before the channel's send promise returns.
    ledger.markTurnStarted("session-1", "turn-1");
    ledger.markSessionBusy("session-1");
    assert.equal(ledger.hasActiveTurn(), true, "accepted delivery is busy before turn.started");
    ledger.markSessionBusy("session-1");
    ledger.markTurnStarted("session-1", "turn-1");
    assert.equal(ledger.hasActiveTurn(), true, "duplicate public lifecycle events do not add a second reservation");
    assert.equal(ledger.markTurnIdle("session-1", "turn-1"), true);
    assert.equal(ledger.hasActiveTurn(), false, "terminal turn hook releases the reservation");
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("turn.started before channel send return still advances the bound wake receipt", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-wake-turn-race-"));
  const ledger = new DeliveryLedger(join(directory, "delivery.sqlite"));
  try {
    const wake = ledger.beginWake({
      wakeId: "wake-turn-race",
      worldId: "world-1",
      agentId: "agent-1",
      sourceIds: ["source"],
      dirtyKeys: ["source:key"],
      mustHandleIds: [],
      rescanRequired: false,
    });
    ledger.transitionWake(wake.wakeId, "dispatching");
    ledger.markTurnStarted("eve-session-race", "turn-race");
    ledger.bindWakeSession(wake.wakeId, "eve-session-race");
    ledger.markSessionBusy("eve-session-race");
    assert.equal(ledger.transitionWake(wake.wakeId, "accepted").status, "context_presented");
    assert.equal(ledger.completeWakeForSession("eve-session-race"), 1);
    assert.equal(ledger.getWake(wake.wakeId).status, "acknowledged");
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});

test("ledger reopen preserves busy until public Eve lifecycle releases it", () => {
  const directory = mkdtempSync(join(tmpdir(), "nemeia-turn-reopen-"));
  const filename = join(directory, "delivery.sqlite");
  let ledger = new DeliveryLedger(filename);
  ledger.markSessionBusy("stale-session");
  assert.equal(ledger.hasActiveTurn(), true);
  ledger.close();
  ledger = new DeliveryLedger(filename);
  try {
    assert.equal(ledger.hasActiveTurn(), true, "opening SQLite is not evidence Eve is idle");
    ledger.clearSessionActivity("stale-session");
    assert.equal(ledger.hasActiveTurn(), false);
  } finally {
    ledger.close();
    rmSync(directory, { recursive: true, force: true });
  }
});
