import type { ResourceRef as GeneratedResourceRef } from "../../../world-client/src/generated/types.ts";

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { readonly [key: string]: JsonValue };

/** A principal derived from Eve's authenticated session, never from model input. */
export interface WorldPrincipal {
  readonly principalId: string;
  readonly principalType: string;
  readonly authenticator: string;
  readonly issuer?: string;
  readonly subject?: string;
}

export interface EveSessionAuthSnapshot {
  readonly current: WorldPrincipal | null;
  readonly initiator: WorldPrincipal | null;
}

// ResourceRef is generated by SpacetimeDB. Keep the runtime seam on the native
// bigint form; world-client/src/json.ts owns its decimal-string boundary.
export type ResourceRef = GeneratedResourceRef;

export interface MissionLogEntry {
  readonly missionId: string;
  readonly description: string;
  readonly lifecycle: "active" | "closing" | "succeeded" | "failed" | "cancelled";
  readonly objectives?: readonly MissionObjectiveSummary[];
  readonly readyObjectiveIds: readonly string[];
  readonly pendingObjectiveIds: readonly string[];
  readonly deadlineAt?: string;
}

export interface MissionObjectiveSummary {
  readonly objectiveId: string;
  readonly description: string;
  readonly dependsOn: readonly string[];
  readonly optional: boolean;
  readonly criterion: JsonValue;
  readonly progressEvidence?: JsonValue;
  readonly recordedAt?: string;
}

export interface WorldViewProjection {
  readonly worldId: string;
  readonly agentId: string;
  readonly worldRevision: string;
  readonly missionLog: readonly MissionLogEntry[];
  readonly summary: Readonly<Record<string, JsonValue>>;
  readonly sourceIds: readonly string[];
  readonly dirtyKeys: readonly string[];
  readonly mustHandleIds: readonly string[];
  readonly rescanRequired: boolean;
  readonly attentionGeneration?: number;
  readonly acquisitionTimes: readonly string[];
  readonly evidence: readonly ResourceRef[];
}

export type WorldReadOperation = "summary" | "mission-log";

export type WorldDetailOperation =
  | "observation-detail"
  | "observation-history"
  | "geometry-detail"
  | "map-history"
  | "event-history"
  | "spatial-frame-detail";

export interface WorldReadRequest {
  readonly worldId: string;
  readonly agentId: string;
  readonly principal: WorldPrincipal;
  readonly operation: WorldReadOperation;
  readonly maxBytes: number;
}

export interface WorldDetailRequest {
  readonly worldId: string;
  readonly agentId: string;
  readonly principal: WorldPrincipal;
  readonly operation: WorldDetailOperation;
  readonly maxBytes: number;
  readonly key?: string;
  readonly observationId?: string;
  readonly mapId?: string;
  readonly subjectId?: string;
  readonly frameId?: string;
  readonly afterSequence?: string;
  readonly afterRevision?: string;
  readonly limit?: number;
}

export interface WorldDetailResult {
  readonly worldId: string;
  readonly agentId: string;
  readonly worldRevision: string;
  readonly sourceId: string;
  readonly value: JsonValue;
}

/** Narrow seam for the generated world-client. It owns authz and current-state reads. */
export interface WorldReadPort {
  readProjection(request: WorldReadRequest): Promise<WorldViewProjection>;
  readDetail?(request: WorldDetailRequest): Promise<WorldDetailResult>;
  /** A pinned context may retire only replaceable attention at this generation. */
  acknowledgeProjection?(generation: number): void | Promise<void>;
}

export interface StepIdentity {
  readonly sessionId: string;
  readonly turnId: string;
  readonly stepIndex: number;
}

export interface ContextFile {
  readonly path: `/world/${string}`;
  readonly content: string;
  readonly byteLength: number;
}

export interface PreparedWorldContext {
  readonly contextId: string;
  readonly step: StepIdentity;
  readonly preparedAt: string;
  readonly worldRevision: string;
  readonly files: readonly ContextFile[];
  readonly sourceIds: readonly string[];
  readonly acquisitionTimes: readonly string[];
}

export interface TrustedWorldBinding {
  readonly worldId: string;
  readonly agentId: string;
  readonly principal: WorldPrincipal;
}
